# PUERTO PARA AZURE
server.port=${PORT:8080}  # usa el puerto asignado por Azure, 8080 si no existe

# Contexto de la aplicación
server.servlet.context-path=/

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
