# PUERTO PARA AZURE
server.port=80

# Contexto de la aplicación
server.servlet.context-path=/

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
